version: "2"
services:
  node:
    build: .
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=taskpot.incubation.van.tasktop.com
      - NPM_CONFIG_LOGLEVEL=debug
    # volumes:
    #   - ./:/home/node/app
    ports:
      - "1234:3000"
    command: "node index.js"